#!/data/data/com.termux/files/usr/bin/bash

# Curtroder Installer
# Author: Current Vai ♚ (Concept) & AI Assistant (Scripting)

# --- Welcome Banner for Installer ---
clear
echo -e "\e[1;32mWelcome to the Curtroder Theme Installer!\e[0m"
echo "This script will set up a dynamic banner and prompt for your Termux."
echo ""

# --- Dependency Check ---
echo -e "\e[1;33m[*] Checking for required packages...\e[0m"
pkg install figlet -y > /dev/null 2>&1
pkg install curl -y > /dev/null 2>&1
echo -e "\e[1;32m[+] Dependencies are satisfied.\e[0m"
echo ""

# --- Get User's Name ---
read -p $'\e[1;33m[*] Please enter the name you want to display: \e[0m' user_name

# If user enters nothing, use a default name
if [ -z "$user_name" ]; then
    user_name="User"
    echo -e "\e[1;31m[!] No name entered. Using default name 'User'.\e[0m"
fi
echo ""

# --- Generate ASCII Art from Name ---
# Using figlet to generate the banner text
# The "-f standard" flag uses a font similar to your original banner
ascii_art=$(figlet -f standard "$user_name")

# --- Backup existing .bashrc ---
if [ -f "$HOME/.bashrc" ]; then
    echo -e "\e[1;33m[*] Backing up your existing .bashrc to .bashrc.bak...\e[0m"
    mv "$HOME/.bashrc" "$HOME/.bashrc.bak"
fi

# --- Create the new .bashrc file using a Here Document ---
echo -e "\e[1;33m[*] Creating new custom .bashrc file...\e[0m"

# The 'EOF' here document allows us to write a multi-line string to a file.
# Variables like $user_name and $ascii_art will be replaced with their values.
cat > "$HOME/.bashrc" << EOF
# ~/.bashrc - Generated by Curtroder

# --- Step 1: Loading Animation ---
clear
echo -e "\e[1;32m$user_name ♚\e[0m"
echo -e "\e[1;33mPlease wait a moment. system is loading\e[0m"
echo ""
echo -n -e "\e[1;31m#loading [\e[0m"
for i in {1..20}; do
    echo -n -e "\e[1;32m█\e[0m"
    sleep 0.1
done
echo -e "\e[1;31m] #Done\e[0m"
sleep 1
clear

# --- Step 2: Welcome Message ---
echo -e "\e[1;32mWelcome $user_name ♚\e[0m"
echo -e "\e[1;36msystem is ready.\e[0m"
echo -e "\e[1;36mNow you can complete your mission.\e[0m"
echo ""

# --- Step 3: The Pinned Banner Function ---
display_banner() {
    # The ASCII Art Banner (Dynamically generated)
    echo -e "\e[1;36m"
    echo "$ascii_art"
    echo -e "\e[0m"

    # Developer Info
    echo -e "\e[1;34m✨ Theme by $user_name | Curtroder v1.0\e[0m"
    echo -e "\e[1;33m© Copyright $(date +%Y) — All Rights Reserved.\e[0m"
    echo -e "\e[1;31m\"I am completely destroyed. Error 304 Not Modified.\"\e[0m"
    
    # Dynamic Info: IP and Date
    echo -e "\n\e[95m📅 \$(date +"%A, %d %B %Y") | ⏰ \$(date +"%I:%M %p")\e[0m"
    if command -v curl >/dev/null 2>&1; then
      IP=\$(curl -s ifconfig.me)
    else
      IP="(curl not found)"
    fi
    echo -e "\e[92m🌐 IP Address:\e[0m \$IP"
    echo ""
}

# --- Pinned Banner Magic ---
clear() {
    /data/data/com.termux/files/usr/bin/clear
    display_banner
}

# --- Step 4: Custom Command Prompt (PS1) ---
PS1='\[\e[1;31m\]┌─[\[\e[1;33m\]\t\[\e[1;31m\]]─[\[\e[1;33m\]$user_name@Curtroder\[\e[1;31m\]]──[\[\e[1;36m\]\w\[\e[1;31m\]]
\[\e[1;31m\]└─> \[\e[0m\]'

# --- Final step: Show the banner for the first time ---
display_banner

EOF

# --- Final Success Message ---
echo ""
echo -e "\e[1;32m[SUCCESS] Curtroder theme has been installed successfully!\e[0m"
echo "Please restart your Termux session to see the changes."
echo "Your old .bashrc was saved as .bashrc.bak"
